// Generated by gencpp from file face_detector/TurnServo.msg
// DO NOT EDIT!


#ifndef FACE_DETECTOR_MESSAGE_TURNSERVO_H
#define FACE_DETECTOR_MESSAGE_TURNSERVO_H

#include <ros/service_traits.h>


#include <face_detector/TurnServoRequest.h>
#include <face_detector/TurnServoResponse.h>


namespace face_detector
{

struct TurnServo
{

typedef TurnServoRequest Request;
typedef TurnServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurnServo
} // namespace face_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::face_detector::TurnServo > {
  static const char* value()
  {
    return "9e8900160e632bc440efbe0cc2cd41d3";
  }

  static const char* value(const ::face_detector::TurnServo&) { return value(); }
};

template<>
struct DataType< ::face_detector::TurnServo > {
  static const char* value()
  {
    return "face_detector/TurnServo";
  }

  static const char* value(const ::face_detector::TurnServo&) { return value(); }
};


// service_traits::MD5Sum< ::face_detector::TurnServoRequest> should match 
// service_traits::MD5Sum< ::face_detector::TurnServo > 
template<>
struct MD5Sum< ::face_detector::TurnServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::face_detector::TurnServo >::value();
  }
  static const char* value(const ::face_detector::TurnServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_detector::TurnServoRequest> should match 
// service_traits::DataType< ::face_detector::TurnServo > 
template<>
struct DataType< ::face_detector::TurnServoRequest>
{
  static const char* value()
  {
    return DataType< ::face_detector::TurnServo >::value();
  }
  static const char* value(const ::face_detector::TurnServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::face_detector::TurnServoResponse> should match 
// service_traits::MD5Sum< ::face_detector::TurnServo > 
template<>
struct MD5Sum< ::face_detector::TurnServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::face_detector::TurnServo >::value();
  }
  static const char* value(const ::face_detector::TurnServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::face_detector::TurnServoResponse> should match 
// service_traits::DataType< ::face_detector::TurnServo > 
template<>
struct DataType< ::face_detector::TurnServoResponse>
{
  static const char* value()
  {
    return DataType< ::face_detector::TurnServo >::value();
  }
  static const char* value(const ::face_detector::TurnServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACE_DETECTOR_MESSAGE_TURNSERVO_H
