// Generated by gencpp from file face_detector/TurnServoResponse.msg
// DO NOT EDIT!


#ifndef FACE_DETECTOR_MESSAGE_TURNSERVORESPONSE_H
#define FACE_DETECTOR_MESSAGE_TURNSERVORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_detector
{
template <class ContainerAllocator>
struct TurnServoResponse_
{
  typedef TurnServoResponse_<ContainerAllocator> Type;

  TurnServoResponse_()
    : errorcode(0)  {
    }
  TurnServoResponse_(const ContainerAllocator& _alloc)
    : errorcode(0)  {
  (void)_alloc;
    }



   typedef int8_t _errorcode_type;
  _errorcode_type errorcode;




  typedef boost::shared_ptr< ::face_detector::TurnServoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_detector::TurnServoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurnServoResponse_

typedef ::face_detector::TurnServoResponse_<std::allocator<void> > TurnServoResponse;

typedef boost::shared_ptr< ::face_detector::TurnServoResponse > TurnServoResponsePtr;
typedef boost::shared_ptr< ::face_detector::TurnServoResponse const> TurnServoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_detector::TurnServoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_detector::TurnServoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face_detector::TurnServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detector::TurnServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detector::TurnServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detector::TurnServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detector::TurnServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detector::TurnServoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_detector::TurnServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2a121016cedc86b73339a40049326bd";
  }

  static const char* value(const ::face_detector::TurnServoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2a121016cedc86bULL;
  static const uint64_t static_value2 = 0x73339a40049326bdULL;
};

template<class ContainerAllocator>
struct DataType< ::face_detector::TurnServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_detector/TurnServoResponse";
  }

  static const char* value(const ::face_detector::TurnServoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_detector::TurnServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 errorcode\n\
\n\
";
  }

  static const char* value(const ::face_detector::TurnServoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_detector::TurnServoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorcode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnServoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_detector::TurnServoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_detector::TurnServoResponse_<ContainerAllocator>& v)
  {
    s << indent << "errorcode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.errorcode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_DETECTOR_MESSAGE_TURNSERVORESPONSE_H
